In [1]:
%load_ext autoreload
%autoreload 2
from logistic import *

In [9]:
N=100
D=10
w = np.ones(D)
b=1
X = np.ones((N,D))

In [4]:
pred = binary_predict(X, w, b)

In [5]:
pred.shape

(100,)

In [10]:
X.shape

(100, 10)

In [11]:
X = np.append(np.ones((N,1)),X,axis=1)

In [12]:
X.shape

(100, 11)

In [13]:
wb = np.append(b,w)

In [14]:
wb.shape

(11,)

In [15]:
run_binary()

ImportError: No module named 'sklearn'

In [17]:
y = np.ones(100)
X = np.ones((100,3))

In [20]:
y.reshape(-1,1)*X

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.

In [21]:
np.zeros(1)

array([ 0.])

In [26]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [30]:
X = np.zeros((100,3))

In [31]:
X[np.arange(100),y.astype(int)]-=1

In [32]:
X

array([[ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.